name: riseandthrive
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74831
title: 'Rise & Thrive - the journey of Awakening'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#cfcfcf'
    - '#010101'
    - '#9f9f9f'
    - '#626262'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
