name: riseandthrive
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9742
title: 'Rise & Thrive - the journey of Awakening'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#cfcfcf'
    - '#010101'
    - '#9f9f9f'
    - '#626262'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
